services:
    db:
      image: mysql:latest
      platform: linux/x86_64
      container_name: mysqldb
      restart: always
      ports:
        - 3306:3306
    #   volumes:
    #     - mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=event